version: "2.2"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: gunicorn myproject.wsgi --bind 0.0.0.0:8000
        env_file: myenv.env
        image: 'docker.myproject'
        depends_on:
            - postgres
        volumes:
            - .:/app

    caddy:
        image: caddy:2.0.0-alpine
        links:
            - web:web
        ports:
            - 80:80
            - 443:443
        volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile

    migrations:
        build:
            context: .
            dockerfile: Dockerfile
        command: python manage.py migrate
        env_file: myenv.env
        image: 'docker.myproject'
        depends_on:
            - postgres
        volumes:
            - .:/app

    postgres:
        image: 'postgres:12.3-alpine'
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: myenv.env

volumes:
  postgres_data:
